Add heroku deploy setup
highlight-run/highlight-onpremise pull request #7
Opened 2021-07-14 23:10 UTC by cameronbrill

2021-07-14 23:45 UTC, jay-khatri requested changes

2021-07-14 23:45 UTC, jay-khatri commented on app.json
> +        }
Can we update the link here to something that makes more sense? not https://docs.highlight.run/docs/authentication-1

2021-07-14 23:47 UTC, cameronbrill commented on app.json
> +        }
I updated it to https://docs.highlight.run/docs/on-premise#heroku-deployment

2021-07-20 02:31 UTC, cameronbrill commented on app.json
> +                "version": "9.6"
```suggestion
                "version": "10"
```

2021-07-22 01:26 UTC, merged